events {}

stream {
    upstream node_backends {
        server app_1:41234;
        server app_2:41234;
        server app_3:41234;
    }

    server {
        listen 7000 udp;
        proxy_pass node_backends;
    }
}